if typeof(window) != 'undefined'
  # dummy so specs will pass after they require('spec_helper')
  _requires = 
    spec_helper: {}
    fs: {}
    
  window.require = (path) ->
    return _requires[path] if _requires[path] isnt undefined
    xhr = new XMLHttpRequest
    # special cases
    # parsers generated by jison
    if path.indexOf('parser') != -1
      real_path = "lib/assets/javascripts/shader-script/src/#{path}.js"
    # util supplied by node, but mirrored by us for use in tests
    else if path == 'util' != -1
      real_path = "spec/javascripts/support/util.js"
    else
      real_path = "src/src/#{path}.js"
    xhr.open 'GET', real_path, false
    xhr.onreadystatechange = ->
      if xhr.readyState == 4 and xhr.status == 200
        _requires[path] = exports = {}
        global = window
        module =
          deprecate: ->
        eval xhr.responseText
    xhr.send null
    
    return _requires[path]
  window.global = window
  