require 'spec_helper'

describe "Rails builtins" do
  include RSpec::Rails::RequestExampleGroup
  
  let :context do
    get '/assets/shader-script.js'
    ExecJS.compile response.body
  end
  
  def simulate(code)
    context.eval <<-end_code
      (function() {
        sim = new ShaderScript.Simulator({fragment: 'void main(void) { #{code} }'});
        sim.start();
        return sim.state.variables;
      })()
    end_code
  end
  
  it "should be exported by SS asset" do
    result = context.eval "ShaderScript.builtins"
    result.should_not be_empty
  end
  
  it "should not produce NaN" do
    variables = simulate 'float x = dot(vec3(1,1,1), vec3(1,1,1));'
    variables['x']['value'].should == 3
  end

  it "should be accessible to simulator as generated by Rails assets" do
    result = simulate "gl_FragColor = vec4(1,1,1,1);"
    result['gl_FragColor']['value'].should == [1,1,1,1]
  end
end
