require 'spec_helper'

describe "Rails builtins" do
  include RSpec::Rails::RequestExampleGroup
  
  before do
    get '/assets/shader-script.js'
    @context = ExecJS.compile response.body
  end
  
  it "should be exported by SS asset" do
    result = @context.eval "ShaderScript.builtins"
    result.should_not be_empty
  end

  it "should be accessible to simulator as generated by Rails assets" do
    result = @context.eval <<-end_code
      (function() {
        sim = new ShaderScript.Simulator({fragment: 'void main(void) { gl_FragColor = vec4(1,1,1,1); }'});
        sim.start();
        return sim.state.variables;
      })()
    end_code
    
    result['gl_FragColor']['value'].should == [1,1,1,1]
  end
end
